# Generated by Django 3.2.5 on 2021-07-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210724_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=155)),
                ('scoops', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.customer')),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
