# Generated by Django 3.2.5 on 2021-07-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210724_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Option',
        ),
    ]
